### ISSUE TITLE
Bug Fix 1:- Issue when Opening a Restocked Item webpage.

### ISSUE THREAD

**Issue by Parth59** [shahrk/ItemStockTracker#12]
The Application crashes when opening a webpage

Following is a video for the same.
https://user-images.githubusercontent.com/22288099/144723159-9c46adca-e796-488f-8868-2d8c5bd27747.mov

**Comment by Parth59** [comment]
Raised the Following Commit :- https://github.com/shahrk/ItemStockTracker/commit/b012915b356121945e2a8533c126b1defb62762a 

Kindly review and revert if it doesn't look good.

**Comment by mithildave** [comment]
The code looks good. Can you please add the video of a working application? Thanks.

**Comment by Parth59** [comment]
Oh Sure adding the video too !

**Comment by Parth59** [comment]
Here's the video
https://user-images.githubusercontent.com/22288099/144723404-385eec3f-b20e-4897-b192-5c0bea587d0e.mov

**Comment by mithildave** [comment]
Ohh the video looks good. Now the bug seems to be gone. Great work! I am closing this issue. Thanks.
