### ISSUE TITLE
Bug fix 2: Fetch discounted price

### ISSUE THREAD

**Issue by Parth59** [shahrk/ItemStockTracker#13]
The application is not fetching prices when an application has discounted Price. This is leading to null values in our prices.

**Comment by Parth59** [comment]
Here is the before Image.


<img width="1440" alt="Screen Shot 2021-12-04 at 3 31 22 PM" src="https://user-images.githubusercontent.com/22288099/144723805-db308452-12be-4221-95d5-e6b2cbd86572.png">

![image](https://user-images.githubusercontent.com/22288099/144723861-aa52f4cd-4246-480d-bd3a-71e481faf713.png)

**Comment by mithildave** [comment]
Seems like Bhargav has proposed a solution for the same. @Parth59 Lets merge and then verify.

**Comment by Parth59** [comment]
Let's merge and verify.

**Comment by Parth59** [comment]
Now it is able to show the price for the lunch box.
![image](https://user-images.githubusercontent.com/22288099/144723971-46f2ec94-1eda-4d66-8cc3-50b086fa8fa6.png)

**Comment by mithildave** [comment]
Looks Good , Closing it. Thanks!
