### ISSUE TITLE
Developer Feature 1:- Add an Install Script for MAC OS.

### ISSUE THREAD

**Issue by Parth59** [shahrk/ItemStockTracker#14]
There are several complications arising due to the Application initially developed using Windows. These complications are creating a host of issues on MACOS. Thus there is an imminent need of the hour to create an install.sh which can be executed on MAC to setup the environment and Maintain cross-compatibility.

**Comment by mithildave** [comment]
I was also facing the same problem on my new MAC.  Lets fix it.

**Comment by Parth59** [comment]
Okay. I have also added the automatic homebrew installation script in the fix. The issues on MACOS are now fixed.
