### ISSUE TITLE
Create a web based version of the tool

### ISSUE THREAD

**Issue by shahrk** [shahrk/ItemStockTracker#4]
The desktop version is tedious to install and maintain. It would be much better for users to have a web-based version. We can create a simple UI where users can log in and add items to track. They can be notified via email if/when the stock/price of the products they add changes.

**Comment by mithildave** [comment]
The plan as discussed it to :
Phase 1. Create a web UI for analytics page
Phase 2. Create a pice tracker for the items , this will have track the price items on that webpage. 
Phase 3. If the prices or stock are changed, user can see it live on the tracking dashboard.

**Comment by Parth59** [comment]
Oh. Sounds good. I have linked the Phase1 with the following issue.:- https://github.com/shahrk/ItemStockTracker/issues/9
We can proceed with creating issues for Phase 2 and Phase3 later.
