### ISSUE TITLE
Show analytics for price

### ISSUE THREAD

**Issue by shahrk** [shahrk/ItemStockTracker#9]
We can show a price chart for a particular period in history. For this, the app would have to keep running on a server.

**Comment by shahrk** [comment]
It could look something like this:

<img width="1228" alt="Screen Shot 2021-11-25 at 5 25 54 PM" src="https://user-images.githubusercontent.com/11090612/143504739-609212e9-4039-4d6e-bb58-f2b9d5ac4ac7.png">

**Comment by Parth59** [comment]
Hi Team, I have reassigned this issue to Nirav. 
He is working on utilizing the streamlit.io library and is gonna use it as our plan for the Phase1 of migration as discussed over here. https://github.com/shahrk/ItemStockTracker/issues/4
